name: CI/CD

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # CI (Continuous Integration)
  backend:
    runs-on: ubuntu-22.04

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL}}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY}}
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"
      - name: Ensure Gradle wrapper is executable
        working-directory: backend
        run: chmod +x ./gradlew
      - name: Run unit tests
        working-directory: backend
        run: ./gradlew test

  frontend:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out the Git repository
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        working-directory: frontend
        run: npm ci
      - name: Build frontend
        working-directory: frontend
        run: npm run build

 # CD (Continuous Deployment)
  deployment-staging:
    if: github.ref == 'refs/heads/staging'
    needs: [backend, frontend]
    runs-on: ubuntu-22.04

    steps:
      - name: Dummy deploy to staging
        run: echo "Deploying to Staging..."

  deployment-production:
    if: github.ref == 'refs/heads/main'
    needs: [backend, frontend]
    runs-on: ubuntu-22.04

    steps:
      - name: Dummy deploy to production
        run: echo "Deploying to Production..."
